In [2]:
import pandas as pd

In [3]:
df = pd.read_excel("bio.xlsx")
df.sample(5)

FileNotFoundError: [Errno 2] No such file or directory: 'bio.xlsx'

In [3]:
df.shape[0]

153203

In [4]:
df.dropna(inplace=True)

In [5]:
df.shape[0]

123190

In [6]:
import numpy as np

In [7]:
df.bio = df.bio.astype(str)

In [10]:
df["unique"] = df.bio.apply(lambda x: "".join(set(x)))

In [11]:
df.sample(10)

,screen_name,score,bio,unique
92559,yasenabi_313,104,إرْحَمْ فِي هذِهِ الدُّنْيا غُرْبَتِی ...\nدر ...,َتِف🌹بّيقاْمرُ.إنشذغلسه#\nدآوکحی
32376,saraheidary10,24,#اللهم_العجل_الولیک_الفرج,معیک#فرو_لهاج
120046,heh_girl1,13,اگه خدا قبول کنه، ایرانی🥸,ک🥸ربدنوقلهاخ،یگ
147867,Pooriaslj1,3,🇮🇷 lawyer 🇮🇷,lwra🇷y🇮e
83932,the_mr_mim,3,ایران شناس🇮🇷\nطبیعت گرد🏕🏜\nحامی حیوانات🐶🐱\nعکا...,ح🏕فبقطاگ🏜مع📷❤ر🐶نش)سلهز🇷خ🇮پ\n(دآو🐱کت،ی
124024,M_tahlilgar57,11,من انقلابی‌ام,م‌بنقلای
138266,KianYazdanpanah,5,🌹https://t.co/YE3U3F0ZXs🌹\nSimple citizen🌱,XEiF:ezcmtls🌹hUS🌱nY.0/p3Z\no
32248,Arash1031317,24,این بیشه گمان مبر که خالیست شاید که پلنگ خفته ...,یفباگمر.نشسلهخدکتپ
146348,zeinabbalaeiy,3,‏‏‏زینب بالایی هستم کارشناسی ادبیات و زبان فار...,حفب‏قاگمعرنشسلهزخدوکت،ی
108161,magma_110,27,من حسینی شده دست امام حسنم \nیا کریم اهل بیت,مکتر\nبنشداسلهحی

In [17]:
chars = np.unique(list(df["unique"].sum()))

In [18]:
len(chars)

5125

In [90]:
with open("chars.npy", "wb") as file:
    np.save(file, chars, allow_pickle=False)

In [91]:
with open("chars.npy", "rb") as file:
    loaded_chars = np.load(file)

In [131]:
def find_users_with_char(char,*,column="cleaned_bio", count=1):
    temp = df[df[column].apply(lambda st: len(re.findall(f'{char}',st))>=count)]
    return temp

In [24]:
df.drop_duplicates("screen_name", inplace=True)

In [25]:
df.shape[0]

81547

In [93]:
find_users_with_char("\uf4f1", column="unique")

,screen_name,score,bio,unique,cleaned_bio
35308,yazahraa_1102,17,در زلف چون کمندش ای دل مپیچ کانجا_x000D_\n.سره...,جیفبxچامعر.نش0‎سلهDز/#ض\nدآو_کتپ,در زلف چون کمندش ای دل مپیچ کانجا_x000D_\n.سره...

In [39]:
df.reset_index(drop=True, inplace=True)

In [41]:
df["cleaned_bio"] = df.bio.str.replace(r'\n+', r'\n', regex=True)

In [74]:
find_users_with_char(128*'\n', column="bio")

,screen_name,score,bio,unique,cleaned_bio
31188,raad_ir,20,‏‏‏‏‏من؟؟\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\...,؟مرُ.\nنشصا‏کتخ،ی,‏‏‏‏‏من؟؟\nمُشتی خاکم، مختصر....

In [76]:
df.iloc[31188]["bio"].count("\n")

128

In [78]:
import re

In [121]:
re.findall(r"(http.+)\s?", df.iloc[81322]["cleaned_bio"])

['https://t.co/d5pemukVcn https://t.co/OfmGF7sqHU… https://t.co/lJonNhB7HA https://t.co/p7tWETYRYj']

In [151]:
df.iloc[81322]["cleaned_bio"]

'I am photographer... https://t.co/d5pemukVcn https://t.co/OfmGF7sqHU… https://t.co/lJonNhB7HA https://t.co/p7tWETYRYj'

In [123]:
find_users_with_char("http", count=4)

,screen_name,score,bio,unique,cleaned_bio
13025,masih_ahmady,50,سیداحمدالحسن یمانی، وصی وفرستاده امام مهدی ع چ...,تصia:emltcفshچاvمعndر.نسلهyr/p\nدoوظکح،ی,سیداحمدالحسن یمانی، وصی وفرستاده امام مهدی ع چ...
61130,ostadfateminia,5,آیت الله سید عبدالله فاطمی نیا\nتلگرام:\n\nhtt...,EViaBb:GfWcltفsPبhUطاTگ4vSمعYdر.Hنش05سلهD/pJQ...,آیت الله سید عبدالله فاطمی نیا\nتلگرام:\nhttps...
81322,msTaffakh,3,I am photographer... https://t.co/d5pemukVcn h...,EVaBF:feWmctlNsqjhUITnYd.HA5Or/pJg…Ro7uGk,I am photographer... https://t.co/d5pemukVcn h...

In [214]:
df["links"] = df["cleaned_bio"].apply(lambda st: re.findall(r'http[@:a-zA-Z%0-9/=?\\\."]+\s?', st))

In [215]:
df["links"].value_counts()

links
[]                                                        79593
[https://t.me/BiChatBot?start=sc]                           269
[https://telegram.me/BChatBot?start=sc]                     141
[https://telegram.me/BiChatBot?start=sc]                     94
[https://t.me/BChatBot?start=sc]                             88
                                                          ...
[http://t.me/NE13581979]                                      1
[https://t.me/HarfinoBot?start=1965d20d59a538]                1
[https://instagram.com/118.m.h.gh?igshid=YmMyMTA2M2Y=]        1
[http://Instagram.com/seyedsoheilrasti]                       1
[https://t.co/H8GrHjeGLM]                                     1
Name: count, Length: 1241, dtype: int64

In [201]:
print(df["links"].value_counts().index[1][0])

('https://t.me/BiChatBot?start=sc', '')

In [170]:
temp = df.copy()

In [172]:
temp.explode(column="links")

,screen_name,score,bio,unique,cleaned_bio,links
0,Seyedhasan_1368,210,«هر عزیزی که فالو نشده لطفاً در پی وی اعلام کن...,🏻🙏️یفطام«ع❤رنشلهز🇷🇮»دوًکپ,«هر عزیزی که فالو نشده لطفاً در پی وی اعلام کن...,NaN
1,malekgamoori,209,یکی بود یکی نبود .\nکه اگه بود روزگارمون این ن...,جفبياگمعر.نكلهز#\nدو_کی,یکی بود یکی نبود .\nکه اگه بود روزگارمون این ن...,NaN
2,manaamini1369,208,خدایا میدانی که دوستت دارم❤\nناشناسم 👇\n\nhttp...,=821aBF:GemltcshUا-Sم❤ر.نش👇سC5هخr6/pg\nدoو?کتی,خدایا میدانی که دوستت دارم❤\nناشناسم 👇\nhttps:...,https://telegram.me/BChatBot?start=sc-228125-5...
3,misagh1401,207,فالو=بک 💯 \nاَللّهُمَّ عَجِّل لِوَلیِّکَ ال...,= َتِجفبّقامعرُن💯له#\nو_کحی,فالو=بک 💯 \nاَللّهُمَّ عَجِّل لِوَلیِّکَ ال...,NaN
4,Mkhadem1346,206,برگـ در زوال می افتد ومیوه درکمال بنگرچگونه می...,ـفبچاگم❤رنسلهزخدوکتی,برگـ در زوال می افتد ومیوه درکمال بنگرچگونه می...,NaN
...,...,...,...,...,...,...
81542,MahnaFard,3,‏‏\n‏Medical intern🇮🇷,cltndM\ni‏a🇷r🇮e,‏‏\n‏Medical intern🇮🇷,NaN
81543,abas1394,3,تاشقایق هست زندگی باید کرد,کربنشداقسهتزیگ,تاشقایق هست زندگی باید کرد,NaN
81544,erfannejad_ir,3,استاد حوزه و دانشگاه,تحدنوشسهازگ,استاد حوزه و دانشگاه,NaN
81545,khademolmahdiii,3,‏‏‏‏\n\n‎‎‎‎‎‎\n‎‎‎,\n‏‎,‏‏‏‏\n‎‎‎‎‎‎\n‎‎‎,NaN
81546,FaNa27291462,3,‏‏‏‏‏‏‏‏‏‏‏‏ماسینه زدیم بی صدا باریدند*\nازهرچ...,‌صجفبچ‏ام*عر.نشسلهزخ\nدآوی,‏‏‏‏‏‏‏‏‏‏‏‏ماسینه زدیم بی صدا باریدند*\nازهرچ...,NaN

In [175]:
del temp

NameError: name 'temp' is not defined

In [173]:
find_users_with_char(r"http", count=2)

,screen_name,score,bio,unique,cleaned_bio,links
517,DwrFamyl,151,گفتنی نیست فنایی که سرآغاز بقاست...معلم دومیا😎...,=8‌Vi2aBb:f😍emctفs✌jبhقا-گ|Svمعر.ن0Cسغلهز🇷r🇮/...,گفتنی نیست فنایی که سرآغاز بقاست...معلم دومیا😎...,[https://t.me/BiChatBot?start=sc-882202-SLfVjV...
762,HamedTeimouri,143,حامی فعالان جریان انقلابی در فضای مجازی -\nفعا...,تiaج:eumctzفsبhقا-معnر.نشسلهزr/pض\nدoوکحی,حامی فعالان جریان انقلابی در فضای مجازی -\nفعا...,"[http://hteimouri.ir, https://eitaa.com/resane..."
802,inside_utopiaa,142,😉نگاهی متفاوت به آرمانشهر✌️بدون روتوش✌️\n\nلین...,iab️:ueج😉ctmlفs✌بhاگمndر.نشلهr/pQپ\n…دآوo_کتیw,😉نگاهی متفاوت به آرمانشهر✌️بدون روتوش✌️\nلینک ...,"[https://twitter.com/inside_utopia/… , https:..."
1556,moharrami_hamed,125,🇮🇷 Art 🇮🇷\n\n https://t.me/Close90 ***...,=8i21aB:emltcsq9h-*d.0AC🇷r/🇮p3g\no?,🇮🇷 Art 🇮🇷\n https://t.me/Close90 *****...,"[https://t.me/Close90 *****************, https..."
3294,montazer1182,101,ارشد مترجمی انگلیسی/رزمی کار/طب سنتی خوان/دهه ...,َِi1aج:eumctlsبhقطاگمعndر.نشسلهزخr/pپg\nدoو_ظ...,ارشد مترجمی انگلیسی/رزمی کار/طب سنتی خوان/دهه ...,"[http://instagram.com/mehrnoushmaleki1, https:..."
...,...,...,...,...,...,...
77557,meyartv,5,معیار رسانه ای است برای بازخوانی اندیشه ها\nشب...,XحBbج:WctsqبhUxقاT4معndر.نشAسلهزخ/pZM\nدoوکتیw,معیار رسانه ای است برای بازخوانی اندیشه ها\nشب...,"[https://t.co/w4UdwMoXqx, https://t.co/tdTnZBb..."
77653,newton1998ph,5,https://t.co/MJnh8hHW20 in jsu\n\nhttps://t.co...,X8Ei2:feWcltsP9jhxn.H0Or/pJMg\nouw,https://t.co/MJnh8hHW20 in jsu\nhttps://t.co/E...,"[https://t.co/MJnh8hHW20 in jsu, https://t.co/..."
79016,jelsaber,4,Co founder \nTaxi360 (https://t.co/AA4WHW4BHU)...,"iaBFf:eWcltmsxhUT4,vnd.H0AC)Dr6/yp3J\nRo(u",Co founder \nTaxi360 (https://t.co/AA4WHW4BHU)...,"[https://t.co/AA4WHW4BHU) , All in(https://t.c..."
81322,msTaffakh,3,I am photographer... https://t.co/d5pemukVcn h...,EVaBF:feWmctlNsqjhUITnYd.HA5Or/pJg…Ro7uGk,I am photographer... https://t.co/d5pemukVcn h...,[https://t.co/d5pemukVcn https://t.co/OfmGF7sq...
81398,rezakhalatbari4,3,‏‏‏‏‏ غلام_زیبنم\n‎‎‎‎‎‎#کربلایی_رضا_خلعتبری:\...,E1B:eWcmtNsPjبh‏ا|معYdر.Hن‎5غلCزخ/pQZJ#ض\no7_...,‏‏‏‏‏ غلام_زیبنم\n‎‎‎‎‎‎#کربلایی_رضا_خلعتبری:\...,[https://t.co/QPZJ57Y1Es‎‎‎‎‎‎ | https://t.co/...

In [199]:
df.iloc[9805].cleaned_bio

'\u200f\u200f\u200f\u200fخبرهای شهرستان بهار را در سایت بهارانه دنبال کنید:\nhttp://www.baharane.ir\u200e\u200e\u200e\u200e\n بهارآنلاین(تلگرام)     \u200e\u200e\u200e\u200e@baharane1\n پیج اینستا گرامی بهار آنلاین \n @\u200f\u200ehttp'

In [258]:
df["cleaned_bio"] = df["cleaned_bio"].apply(lambda st: re.sub(r'https?:\/\/[a-zA-Z0-9\-._~:/?#\[\]@!$&\'()*+,;=%]+(\s?)', "\1", st))

In [260]:
df.drop("tcleaned_bio", inplace=True, axis = 1)

In [262]:
df.drop("unique", inplace=True, axis = 1)

In [295]:
df.sample(50)

,screen_name,score,bio,cleaned_bio,links
48661,masoud__sdghi,9,روزی که تو آمدی به دنیا عریان\nجمعی به تو خندا...,روزی که تو آمدی به دنیا عریان\nجمعی به تو خندا...,[]
21129,sabzjan1,33,عزیزِ جانم:) \nفالو=بک☂️\nعاشق عکاسیم😉📸✌\nدست ...,عزیزِ جانم:) \nفالو=بک☂️\nعاشق عکاسیم😉📸✌\nدست ...,[]
8251,Denizzdann,67,🤞🤞🔥🔥🔥🏖️🏖️🏖️\nخودش میدونه...,🤞🤞🔥🔥🔥🏖️🏖️🏖️\nخودش میدونه...,[]
64819,Faranak90174457,4,باربی لک الحمد کما ینبغی لجلال وجهک وعظیم سلطانک,باربی لک الحمد کما ینبغی لجلال وجهک وعظیم سلطانک,[]
44295,muntazer__313,11,به نام خالق بی همتا\nاَللّهُمَّ عَجِّل لِوَلیِ...,به نام خالق بی همتا\nاَللّهُمَّ عَجِّل لِوَلیِ...,[]
53815,shayegh_hosein,7,اینجا محل مشقه جنگه!\nالهی تو زمین اصلی زمینگی...,اینجا محل مشقه جنگه!\nالهی تو زمین اصلی زمینگی...,[]
24000,hesam_shamshiri,28,‏‏,‏‏,[]
320,mohamadtalbipor,160,به امثال مامیگند مدافع سلامت\nچه کار زیبایی اس...,به امثال مامیگند مدافع سلامت\nچه کار زیبایی اس...,[]
18133,ljtm38991248,38,ما انتقام اشک رهبر و خون حاج قاسم رو از \nمناف...,ما انتقام اشک رهبر و خون حاج قاسم رو از \nمناف...,[]
58644,mohsen20370157,5,‏‏‏««اللهم عجل لولیک الفرج »»\nفالو=بک,‏‏‏««اللهم عجل لولیک الفرج »»\nفالو=بک,[]
71055,targhi65,3,‏متاهل و پدر فاطمه کوچولو\n\n‏‏‏‏زنده ام به عش...,‏متاهل و پدر فاطمه کوچولو\n‏‏‏‏زنده ام به عشق ...,[]
38079,Taleb02875870,15,ابن الوقت,ابن الوقت,[]
73072,alihpgh,21,استاذ في الحوزة العلمية، دكتوراه فقه التربية، ...,استاذ في الحوزة العلمية، دكتوراه فقه التربية، ...,[]
49120,99_mikaeil,9,‏‏( فالو=فالو),‏‏( فالو=فالو),[]
73134,Amin__Mohammadi,20,بنده خدا + مهندس برق,بنده خدا + مهندس برق,[]
16773,Sahandazad4,41,‏‏‏فعلاً هیچی...,‏‏‏فعلاً هیچی...,[]
49634,shahravan99,9,دُنیا‌همه‌هیچُ‌اَهل‌دنیا‌همه‌هیچ ،ای‌هیچ‌برایِ...,دُنیا‌همه‌هیچُ‌اَهل‌دنیا‌همه‌هیچ ،ای‌هیچ‌برایِ...,[]
11957,zaman_zohour,53,‏‏‏‏‏‏‏🗞‏هفته نامه رسمی انصار امام مهدی (ع) و ...,‏‏‏‏‏‏‏🗞‏هفته نامه رسمی انصار امام مهدی (ع) و ...,[http://telegram.me/zaman]
63110,pesare_khak,4,همیشه حرف‌های خوب رو آدم‌های خوب نمیزنن / بیزا...,همیشه حرف‌های خوب رو آدم‌های خوب نمیزنن / بیزا...,[]
3214,Ahmadreza78274,102,دانشجوی مدیریت،علاقه‌مند به امور اجتماعی.\n🎮📽⚽...,دانشجوی مدیریت،علاقه‌مند به امور اجتماعی.\n🎮📽⚽...,[]
79729,m_r_ansari65,3,زندگی صحنه یکتای هنرمندی ماست بورس باز - مشاور...,زندگی صحنه یکتای هنرمندی ماست بورس باز - مشاور...,[]
20653,hajkamal_60,33,آرام آرام همه چیز خوب می‌شود...,آرام آرام همه چیز خوب می‌شود...,[]
14609,yasinrezai00,46,محصلی از حوالی کرج😉\nحسینی بودنم به کسی ربط ند...,محصلی از حوالی کرج😉\nحسینی بودنم به کسی ربط ند...,[]
55775,khajeh_monir_ir,6,‏‏فعال انقلابی/ایران پرست\n\nفرزند ‎‎#حزب_الله,‏‏فعال انقلابی/ایران پرست\nفرزند ‎‎#حزب_الله,[]
78297,AmirhesamEslami,4,"#QasemSoleimani is more than a Hero, he is a S...","#QasemSoleimani is more than a Hero, he is a S...",[]
52053,BenyaminMarandi,8,‏‏محمدصالح،\nپسرم تمام زندگی من.\nعاشق کتابم و...,‏‏محمدصالح،\nپسرم تمام زندگی من.\nعاشق کتابم و...,[]
37400,bwbwly51,15,#سید_اهل_قلم :\nهرگز جز برای خدا کار مکن!!,#سید_اهل_قلم :\nهرگز جز برای خدا کار مکن!!,[]
34685,skwt43183195,17,باید خندید برغمی بی پایان,باید خندید برغمی بی پایان,[]
62348,SarhaddiShahin,5,مگر در جستجوی ربنایی تازه باشیم,مگر در جستجوی ربنایی تازه باشیم,[]
66488,matin358858501,4,وقتی امام عاشقان غایب است اطاعت از خامنه ای وا...,وقتی امام عاشقان غایب است اطاعت از خامنه ای وا...,[]
16712,ErfanAlipour12,41,از سر گذشت سر گذشت ماست,از سر گذشت سر گذشت ماست,[]
41508,teleg_r50,13,حتی مثبت ترین جملات با لحن بد، بدترین نتیجه رو...,حتی مثبت ترین جملات با لحن بد، بدترین نتیجه رو...,[]
62098,dhh_hshtady,5,دهه هشتادی ها انقلاب را به نقطه اصلی خودش خواه...,دهه هشتادی ها انقلاب را به نقطه اصلی خودش خواه...,[]
36391,mm1361zz,16,‏‏صلی الله علیکِ یا فاطمه/اللهم عجل لولیک الفر...,‏‏صلی الله علیکِ یا فاطمه/اللهم عجل لولیک الفر...,[]
57026,Mmahdy_F,6,‏نوکر ارباب,‏نوکر ارباب,[]
79868,Ali1111Z,3,در سایه نشسته‌ام به توییتر می نگرم...,در سایه نشسته‌ام به توییتر می نگرم...,[]
21965,Marzie46995878,31,طَمِّني يا الله ، فَأنا مَملوءٌ بِالخَوف \n ...,طَمِّني يا الله ، فَأنا مَملوءٌ بِالخَوف \n ...,[]
60234,haana_15,5,‏‏آدم باید خودش باشه\nمگر اینکه خودش آدم خوبی ...,‏‏آدم باید خودش باشه\nمگر اینکه خودش آدم خوبی ...,[]
14837,RezaMoghadam75,45,کارشناس ارشد روان شناسی/اردیبهشت ماهی پرسپولیس...,کارشناس ارشد روان شناسی/اردیبهشت ماهی پرسپولیس...,[]
2936,hajkmal12,105,💢من عملیاتی ام 💢,💢من عملیاتی ام 💢,[]
54828,mohammadtaha35,7,هر چه سیاهی شب بیشتر می‌شود صبح نزدیک‌تر است ....,هر چه سیاهی شب بیشتر می‌شود صبح نزدیک‌تر است ....,[]
39103,sharamraeisi,14,سرباز ولایت\n\nتازه واردم لطفا حمایت کنید\nفال...,سرباز ولایت\nتازه واردم لطفا حمایت کنید\nفالو ...,[]
57660,FKalavand,6,mis\nbakhtiyari\nfootblallist,mis\nbakhtiyari\nfootblallist,[]
38261,ali04618621,15,🖤‏هیچم🖤,🖤‏هیچم🖤,[]
67799,Alireza31645036,3,‏‏‏‏‏‏‏‏‏ویرانه نه آن است که جمشید بنا کرد\n\n...,‏‏‏‏‏‏‏‏‏ویرانه نه آن است که جمشید بنا کرد\n و...,[]
38554,filmdirector20,15,Photographer and film director\nWest dream\nDr...,Photographer and film director\nWest dream\nDr...,[]
50595,jaber_khan9731,8,‏‏‏‏‏‏‏‏‏‏‏‏‏‏‏‏‏‏سیزدهمین نواده نادر شاه افشا...,‏‏‏‏‏‏‏‏‏‏‏‏‏‏‏‏‏‏سیزدهمین نواده نادر شاه افشا...,[]
17191,milioo24,40,کوردم فدای ذره ذره خاک ایران ...,کوردم فدای ذره ذره خاک ایران ...,[]
69849,frdyn79015948,3,ایران آزاد خواهد شد به امید پیروزی ایران,ایران آزاد خواهد شد به امید پیروزی ایران,[]
44005,Mohammad_Shfn,11,🏠 اراک 🏠,🏠 اراک 🏠,[]

In [240]:
find_users_with_char("http",column="tcleaned_bio")

,screen_name,score,bio,unique,cleaned_bio,links,tcleaned_bio
5504,Uu2Rbe,82,سلام خوش اومدید این دو جا از من حمایت کنید لای...,=تi21aجf:emltcفsq9hxاvمnd.نشسلزخr/pgدoو7?کحیwk,سلام خوش اومدید این دو جا از من حمایت کنید لای...,"[https , https://www.instagram.com/invites/con...",سلام خوش اومدید این دو جا از من حمایت کنید لای...
9805,baharane5,61,‏‏‏‏خبرهای شهرستان بهار را در سایت بهارانه دنب...,i1ab:جetبh‏اگمn@ر.نش‎)سلهخr/pپ\n(دآکتیw,‏‏‏‏خبرهای شهرستان بهار را در سایت بهارانه دنب...,[http://www.baharane.ir],‏‏‏‏خبرهای شهرستان بهار را در سایت بهارانه دنب...
10988,Molok57489497,56,از فرزندان ده چهل هستم\nعاشق هنرهای دستی هستم\...,ج:tفsبhچقطاگمعرنشسلهز/p#\nدو_کتی,از فرزندان ده چهل هستم\nعاشق هنرهای دستی هستم\...,[https://],از فرزندان ده چهل هستم\nعاشق هنرهای دستی هستم\...
13025,masih_ahmady,50,سیداحمدالحسن یمانی، وصی وفرستاده امام مهدی ع چ...,تصia:emltcفshچاvمعndر.نسلهyr/p\nدoوظکح،ی,سیداحمدالحسن یمانی، وصی وفرستاده امام مهدی ع چ...,"[https:http://almahdyoon.co\n, https:http://va...",سیداحمدالحسن یمانی، وصی وفرستاده امام مهدی ع چ...
40770,meghdad_hosein,13,اینستاگرام: http:/instagram@thehoseintataei,ia:emtshاگمn@رنسr/pgoتی,اینستاگرام: http:/instagram@thehoseintataei,[http:/instagram@thehoseintataei],اینستاگرام: http:/instagram@thehoseintataei
67322,OzvTazmini,3,کلاهبردار: مسلم مرادی\nشماره تلفن: 09167635643...,8i21a:ezmtف9بhاTگ4vمnر.نش05سلغOهزخ6/p3پ\nدو7کت،ی,کلاهبردار: مسلم مرادی\nشماره تلفن: 09167635643...,"[http://T.me/OzvTazmini\n, http://]",کلاهبردار: مسلم مرادی\nشماره تلفن: 09167635643...
72926,kzareeiofficial,24,#‏‏‏‏‏‏‏‏روانشناس\n #Psychologist\n\n\nhttps//...,iafezcltmsPh‏قاIمnعر.نش‎سلهزyr/p#g\noو_کیwk,#‏‏‏‏‏‏‏‏روانشناس\n #Psychologist\nhttps//www....,[https//www.Instagram.com/k],#‏‏‏‏‏‏‏‏روانشناس\n #Psychologist\nhttps//www....
73841,alireza16054371,14,http:// #Ph.D stu #Geo.Env #sbu\n#M.Sc #Enviro...,ت‌Eiab️:ecmtl🗺فsPیبhچ🌍اSvndر.نسلهDز🇷ry/🇮p🌐پ#M...,http:// #Ph.D stu #Geo.Env #sbu\n#M.Sc #Enviro...,[http:// ],http:// #Ph.D stu #Geo.Env #sbu\n#M.Sc #Enviro...

In [255]:
df.iloc[64213].screen_name

'wwwTpmdsdotcom'

In [251]:
for _ in df['links'].value_counts().index:
    if re.findall(r'[ا-ی]', "".join(_)):
        print(_)

In [252]:
df[df.links.apply(lambda arr: len(arr) > 0)].sample(50).links

64213                       [https://youtube.com/c/TPMDS]
49131            [https://telegram.me/BiChatBot?start=sc]
5110     [https://twitter.com/search?q=from%3A%40mahmood]
12510                         [https://t.me/oneofthemmmm]
31007             [https://t.me/BiChatBot?start=66259225]
52572                     [https://t.me/uSendBot?start=u]
77622                           [https://t.co/ob8gQ3rHj1]
12880                            [https://t.me/gheyniche]
36540                        [http://B.Sc , http://M.Sc ]
2840      [https://twitter.com/search?q=from%3A%40setiaa]
5184                          [https://b2n.ir/AliPlatini]
9322                    [https://t.me/BiChatBot?start=sc]
5685                [https://www.instagram.com/masoomehf]
8882                    [https://t.me/BiChatBot?start=sc]
66341             [https://telegram.me/BChatBot?start=sc]
31260        [https://www.instagram.com/salman.khorasan/]
8354              [https://telegram.me/BChatBot?start=sc]
5454                [http://instagram.com/invites/contac]
35001                           [https://t.co/8dMtUiwrC2]
18499                   [https://t.me/BiChatBot?start=sc]
10401                              [http://t.me/bakakan1]
22626                    [https://t.me/BChatBot?start=sc]
18478                    [https://t.me/BChatBot?start=sc]
67720        [https://www.instagram.com/seyedjavadzakeri]
44890             [https://telegram.me/BChatBot?start=sc]
44368                              [http://bazisell.com ]
22523                    [https://HarfBeMan.pw/@na2henas]
14452                             [http://t.me/HidenChat]
13782                        [http://t.me/HarfinoBot?sta]
820           [https://Twitter.com/search?q=from:@sobhan]
66360             [https://www.instagram.com/surin.trade]
75246                           [https://t.co/6A2zCqYI4a]
51897                    [https://t.me/BChatBot?start=sc]
37942                     [https://t.me/uSendBot?start=u]
78590                           [https://t.co/GTyxMBuDOS]
41917                [http://instagram.com/sabamohamadi5]
7121       [https://telegram.me/TeleCommentsBot?start=sc]
63619                                   [https://t.co/jl]
11419            [https://telegram.me/BiChatBot?start=sc]
43340         [https://t.me/Harfmanrobot?start=328210992]
28355                   [https://t.me/BiChatBot?start=sc]
39320              [http://telegram.me/bchatBot?start=\n]
68115                        [http://Instagram.com/matin]
31384                   [https://t.me/BiChatBot?start=sc]
43148                                     [http://M.Sc. ]
65559                      [https://instagram.com/soheil]
44349                           [http://t.me/JNikimaleki]
59245                        [http://t.me/MohamadMoghadd]
47573                      [http://Turkey.Team:Barcelona]
15137      [https://t.me/HarfBeManBOT?start=NzU1NDAyMjM2]
Name: links, dtype: object

In [232]:
find_users_with_char("Tarafdari")

,screen_name,score,bio,unique,cleaned_bio,links,tcleaned_bio
42578,iamthehosein,12,Sport Journalist at http://Tarafdari.Com\n. \n...,EiabFf:ezmltcsPhاT-Sگvمndر.نشCهr/pJMg\noدوuی,Sport Journalist at http://Tarafdari.Com\n. \n...,[http://Tarafdari.Com\n],Sport Journalist at . \nSoccer Commentator at...

In [257]:
df.iloc[47573].screen_name

'erajenoori1998'

In [267]:
df.to_csv("Processed.csv", index=False)

In [268]:
loaded_df = pd.read_csv("Processed.csv")

In [269]:
loaded_df

,screen_name,score,bio,cleaned_bio,links
0,Seyedhasan_1368,210,«هر عزیزی که فالو نشده لطفاً در پی وی اعلام کن...,«هر عزیزی که فالو نشده لطفاً در پی وی اعلام کن...,[]
1,malekgamoori,209,یکی بود یکی نبود .\nکه اگه بود روزگارمون این ن...,یکی بود یکی نبود .\nکه اگه بود روزگارمون این ن...,[]
2,manaamini1369,208,خدایا میدانی که دوستت دارم❤\nناشناسم 👇\n\nhttp...,خدایا میدانی که دوستت دارم❤\nناشناسم 👇\n,['https://telegram.me/BChatBot?start=sc']
3,misagh1401,207,فالو=بک 💯 \nاَللّهُمَّ عَجِّل لِوَلیِّکَ ال...,فالو=بک 💯 \nاَللّهُمَّ عَجِّل لِوَلیِّکَ ال...,[]
4,Mkhadem1346,206,برگـ در زوال می افتد ومیوه درکمال بنگرچگونه می...,برگـ در زوال می افتد ومیوه درکمال بنگرچگونه می...,[]
...,...,...,...,...,...
81542,MahnaFard,3,‏‏\n‏Medical intern🇮🇷,‏‏\n‏Medical intern🇮🇷,[]
81543,abas1394,3,تاشقایق هست زندگی باید کرد,تاشقایق هست زندگی باید کرد,[]
81544,erfannejad_ir,3,استاد حوزه و دانشگاه,استاد حوزه و دانشگاه,[]
81545,khademolmahdiii,3,‏‏‏‏\n\n‎‎‎‎‎‎\n‎‎‎,‏‏‏‏\n‎‎‎‎‎‎\n‎‎‎,[]
81546,FaNa27291462,3,‏‏‏‏‏‏‏‏‏‏‏‏ماسینه زدیم بی صدا باریدند*\nازهرچ...,‏‏‏‏‏‏‏‏‏‏‏‏ماسینه زدیم بی صدا باریدند*\nازهرچ...,[]

In [281]:
(df['cleaned_bio'] == loaded_df['cleaned_bio']).sum()

81547

In [292]:
df['links'].apply(str) == loaded_df.links

0        True
1        True
2        True
3        True
4        True
         ...
81542    True
81543    True
81544    True
81545    True
81546    True
Name: links, Length: 81547, dtype: bool

In [288]:
loaded_df.iloc[2]['links']

"['https://telegram.me/BChatBot?start=sc']"

In [294]:
df.compare(loaded_df)

                                         links  \
                                          self
0                                           []
1                                           []
2      [https://telegram.me/BChatBot?start=sc]
3                                           []
4                                           []
...                                        ...
81542                                       []
81543                                       []
81544                                       []
81545                                       []
81546                                       []


                                           other
0                                             []
1                                             []
2      ['https://telegram.me/BChatBot?start=sc']
3                                             []
4                                             []
...                                          ...
81542                                         []
81543                                         []
81544                                         []
81545                                         []
81546                                         []

[81547 rows x 2 columns]